Fix wrong owner on log file
Before this commit running the script as root created the log file as
root user, then it was impossible to run the script as user without
manually removing the log file.

diff --git a/cleanupdate b/cleanupdate
--- a/cleanupdate
+++ b/cleanupdate
@@ -36,48 +36,22 @@ if [[ "$LANG" =~ "it_IT" ]]; then
   _LNG="ita"
 fi
 
-#
-# Function that prints warning message and wait for user input when the script
-#  terminates unexpectedly.
-#
-function exit_trap {
-  echo 1>&2
-  echo 1>&2
-  if [[ $_LNG = ita ]]; then
-    echo "Lo script è terminato in modo non previsto. È possibile"\
-      "rileggere i messaggi di errore nel file '/tmp/cleanupdate.log'"\
-      "fino al prossimo riavvio." 1>&2
-    echo "Premere un tasto qualsiasi per uscire." 1>&2
-  else
-    echo "Script terminated unexpectedly. It is possible to read error"\
-      "messages also in '/tmp/cleanupdate.log' until the next reboot."\
-      1>&2
-    echo "Press any key to exit." 1>&2
-  fi
-  read -rs -n1
-}
-
-# Define trap for any type of EXIT, calls the previous defined function
-trap exit_trap EXIT
-
-# Initialise logfile with current date and time
-logfile="/tmp/cleanupdate.log"
-echo -e "\\n$(/bin/date -R) --- Cleanupdate errors log\\n" >> $logfile
-
-# Define little function to print errors in stderr and in a logfile
-function print_errors {
-  /bin/tee --append $logfile 1>&2
-}
+# This script should not be executed as root.
+if [[ "$(id -u)" = "0" ]]
+then
+  echo "This script should not be executed as root." 1>&2
+  echo "Please retry running it as user." 1>&2
+  exit 126
+fi
 
 # Check if /bin/tput is installed, otherwise some commands can't work
 if [[ ! -x /bin/tput ]]; then
   if [[ $_LNG = ita ]]; then
     echo "ERRORE: /bin/tput non è presente sul sistema, verificare che la"\
-      "libreria 'ncurses' sia installata correttamente." | print_errors
+      "libreria 'ncurses' sia installata correttamente." 1>&2
   else
     echo "ERROR: /bin/tput is not present in the system, verify that"\
-      "verify that 'ncurses' library is properly installed." | \
-      print_errors
+      "verify that 'ncurses' library is properly installed." 1>&2
   fi
   exit 1
 fi
@@ -95,14 +69,42 @@ readonly _BOLD _NORMAL _RED _GREEN _YELLOW _AQUA
 if [[ -z $HOME ]]; then
   if [[ $_LNG = ita ]]; then
     echo "ERRORE: la variabile d'ambiente $HOME è vuota,"\
-      "è impossibile ottenere il percorso per la home dell'utente." | \
-      print_errors
+      "è impossibile ottenere il percorso per la home dell'utente." 1>&2
   else
     echo "ERROR: $HOME variable not set properly,"\
-      "it is impossible to get the path of user's home." | print_errors
+      "it is impossible to get the path of user's home." 1>&2
   fi
   exit 1
 fi
+
+#
+# Function that prints warning message and wait for user input when the script
+#  terminates unexpectedly.
+#
+function exit_trap {
+  echo 1>&2
+  echo 1>&2
+  if [[ $_LNG = ita ]]; then
+    echo "Lo script è terminato in modo non previsto. È possibile"\
+      "rileggere alcuni messaggi di errore nel file '/tmp/cleanupdate.log'"\
+      "fino al prossimo riavvio." 1>&2
+    echo "Premere un tasto qualsiasi per uscire." 1>&2
+  else
+    echo "Script terminated unexpectedly. It is possible to read some error"\
+      "messages also in '/tmp/cleanupdate.log' until the next reboot."\
+      1>&2
+    echo "Press any key to exit." 1>&2
+  fi
+  read -rs -n1
+}
+
+# Define trap for any type of EXIT, calls the previous defined function
+trap exit_trap EXIT
+
+# Define little function to print errors in stderr and in a logfile
+function print_errors {
+  /bin/tee --append "$logfile" 1>&2
+}
 
 #
 # Function to convert file size in a format easier to read, it receives file
@@ -225,19 +227,6 @@ function qst_msg {
 }
 
 #
-# Function to check if the user is root.
-# This script should not be executed as root.
-#
-function check_root {
-  if [[ "$(id -u)" = "0" ]]
-  then
-    echo "This script should not be executed as root." | print_errors
-    echo "Please retry running it as user." | print_errors
-    exit 126
-  fi
-}
-
-#
 # Function to check arguments passed to the script.
 # This script doesn't accept any argument.
 #
@@ -268,7 +257,7 @@ function check_args {
 #  wants to remove them.
 #
 function orph_pkgs {
-  echo -e "\\nStart orph_pkgs()\\n" >> $logfile
+  echo -e "\\nStart orph_pkgs()\\n" >> "$logfile"
   echo
   if [[ $_LNG = ita ]]; then
     echo "Ricerca pacchetti orfani in corso..."
@@ -325,7 +314,7 @@ function orph_pkgs {
 # Database sync, package upgrade, AUR upgrade.
 #
 function sys_update {
-  echo -e "\\nStart sys_update()\\n" >> $logfile
+  echo -e "\\nStart sys_update()\\n" >> "$logfile"
   if [[ $_LNG = ita ]]; then
     echo " ${_BOLD}::Aggiornamento del sistema::${_NORMAL} "
   else
@@ -516,7 +505,7 @@ function sys_update {
 # Orphaned packages cleaning, cache cleaning, database optimization.
 #
 function clean_pkg {
-  echo -e "\\nStart clean_pkg()\\n" >> $logfile
+  echo -e "\\nStart clean_pkg()\\n" >> "$logfile"
   if [[ $_LNG = ita ]]; then
     echo " ${_BOLD}::Pulizia pacchetti::${_NORMAL} "
   else
@@ -605,7 +594,7 @@ function clean_pkg {
   local -a pacnews=""
   while IFS= read -r -d '' file; do
     pacnews[i++]="$file"
-  done < <(/bin/find /etc -name "*.pacnew" -print0 2>>$logfile)
+  done < <(/bin/find /etc -name "*.pacnew" -print0 2>>"$logfile")
   set -o pipefail
   local -a orphan_pacnews=""
   if [[ -n ${pacnews[0]} ]]; then
@@ -660,7 +649,7 @@ function clean_pkg {
 # Cache & thumbs cleaning, residual file cleaning, trash cleaning.
 #
 function clean_file {
-  echo -e "\\nStart clean_file()\\n" >> $logfile
+  echo -e "\\nStart clean_file()\\n" >> "$logfile"
   if [[ $_LNG = ita ]]; then
     echo " ${_BOLD}::Pulizia file::${_NORMAL} "
   else
@@ -732,7 +721,7 @@ function clean_file {
   while IFS= read -r -d '' file; do
     obsoletelogs[i++]="$file"
   done < <(/bin/find /var/log -name journal -prune -o \( -type f -ctime +90 \
-    -print0 \) 2>>$logfile)
+    -print0 \) 2>>"$logfile")
   set -o pipefail
   if [[ -n ${obsoletelogs[0]} ]]; then
     # Print every obsolete log file
@@ -786,18 +775,18 @@ function clean_file {
   local oldsize=0
   if [[ -d "$HOME/.thumbnails" ]]; then
     oldsize=$(echo "$oldsize+$( /bin/find "$HOME/.thumbnails" -type f\
-      -atime +30 -print0 2>>$logfile | /bin/du --files0-from=- -cb |\
+      -atime +30 -print0 2>>"$logfile" | /bin/du --files0-from=- -cb |\
       /bin/tail -1 | /bin/cut -f 1 )" | bc)
     oldsize=$(echo "$oldsize+$( /bin/find "$HOME/.thumbnails" -empty -type d\
-      -atime +30 -print0 2>>$logfile | /bin/du --files0-from=- -cb |\
+      -atime +30 -print0 2>>"$logfile" | /bin/du --files0-from=- -cb |\
       /bin/tail -1 | /bin/cut -f 1 )" | bc)
   fi
   if [[ -d "$HOME/.cache" ]]; then
     oldsize=$(echo "$oldsize+$( /bin/find "$HOME/.cache" -name pacaur\
-      -prune -o \( -type f -atime +30 -print0 \) 2>>$logfile | /bin/du\
+      -prune -o \( -type f -atime +30 -print0 \) 2>>"$logfile" | /bin/du\
       --files0-from=- -cb | /bin/tail -1 | /bin/cut -f 1 )" | bc)
     oldsize=$(echo "$oldsize+$( /bin/find "$HOME/.cache" -name pacaur\
-      -prune -o \( -empty -type d -atime +30 -print0 \) 2>>$logfile | /bin/du\
+      -prune -o \( -empty -type d -atime +30 -print0 \) 2>>"$logfile" | /bin/du\
       --files0-from=- -cb | /bin/tail -1 | /bin/cut -f 1 )" | bc)
   fi
   set -o pipefail
@@ -868,28 +857,28 @@ function clean_file {
     "$HOME/.cache" -prune -o -path "$HOME/.thumbnails" -prune -o\
     -path "$HOME/.mozilla" -prune -o -path "$HOME/.thunderbird" -prune\
     -o -path "*/.git" -prune -o \( -type f -atime +1 -name "*~"\
-    -user "$USER" -print0 \) 2>>$logfile)
+    -user "$USER" -print0 \) 2>>"$logfile")
   while IFS= read -r -d '' file; do
     residfiles[i++]="$file"
   done < <(/bin/find "$HOME" -name "*Steam*" -prune -o -path\
     "$HOME/.cache" -prune -o -path "$HOME/.thumbnails" -prune -o\
     -path "$HOME/.mozilla" -prune -o -path "$HOME/.thunderbird" -prune\
     -o -path "*/.git" -prune -o \( -type f -atime +1 -name ".*.swp"\
-    -user "$USER" -print0 \) 2>>$logfile)
+    -user "$USER" -print0 \) 2>>"$logfile")
   while IFS= read -r -d '' file; do
     residfiles[i++]="$file"
   done < <(/bin/find "$HOME" -name "*Steam*" -prune -o -path\
     "$HOME/.cache" -prune -o -path "$HOME/.thumbnails" -prune -o\
     -path "$HOME/.mozilla" -prune -o -path "$HOME/.thunderbird" -prune\
     -o -path "*/.git" -prune -o -name "Desktop.ini" -user "$USER"\
-    -print0 2>>$logfile)
+    -print0 2>>"$logfile")
   while IFS= read -r -d '' file; do
     residfiles[i++]="$file"
   done < <(/bin/find "$HOME" -name "*Steam*" -prune -o -path\
     "$HOME/.cache" -prune -o -path "$HOME/.thumbnails" -prune -o\
     -path "$HOME/.mozilla" -prune -o -path "$HOME/.thunderbird" -prune\
     -o -path "*/.git" -prune -o -name "Thumbs.db" -user "$USER" -print0\
-    2>>$logfile)
+    2>>"$logfile")
   set -o pipefail
   if [[ -n ${residfiles[0]} ]]; then
     # Print every residual file
@@ -950,7 +939,7 @@ function clean_file {
     while IFS= read -r -d '' file; do
       trashfiles[i++]="$file"
     done < <(/bin/find "$HOME/.local/share/Trash/files" -mindepth 1\
-      -maxdepth 1 -print0 2>>$logfile)
+      -maxdepth 1 -print0 2>>"$logfile")
     set -o pipefail
     local trashsize=0
     if [[ -n ${trashfiles[0]} ]]; then
@@ -1017,7 +1006,7 @@ function clean_file {
 # Function containing pacman troubleshooting
 #
 function trouble_shoot {
-  echo -e "\\nStart trouble_shoot()\\n" >> $logfile
+  echo -e "\\nStart trouble_shoot()\\n" >> "$logfile"
   local again=true
   local twidth
   twidth=$(tput cols)
@@ -1364,7 +1353,10 @@ function main {
 # Enable debug
 #set -x
 
-check_root
+# Initialise logfile with current date and time.
+logfile="/tmp/cleanupdate.log"
+echo -e "\\n$(/bin/date -R) --- Cleanupdate errors log\\n" >> "$logfile"
+
 check_args "$@"
 
 # Launch the long search for residual file and put everything in background,
@@ -1373,8 +1365,8 @@ check_args "$@"
 if ! (/bin/find "$HOME" -name "*Steam*" -prune -o -path "$HOME/.cache" -prune -o\
   -path "$HOME/.thumbnails" -prune -o -path "$HOME/.mozilla" -prune -o\
   -path "$HOME/.thunderbird" -prune -o -path "*/.git" -prune -o\
-  -print >/dev/null 2>>$logfile &) ; then
-  echo "Errors running initial background 'find' job." >> $logfile
+  -print >/dev/null 2>>"$logfile" &) ; then
+  echo "Errors running initial background 'find' job." >> "$logfile"
 fi
 
 main
