Fixed error messages redirection
Using a function works better to redirect error messages in a file and
print on stderr.
Minor addition to italian documentation.

diff --git a/cleanupdate b/cleanupdate
--- a/cleanupdate
+++ b/cleanupdate
@@ -40,12 +40,16 @@ fi
 #  terminates unexpectedly.
 #
 function exit_trap {
-	echo
+	echo 1>&2
 	if [[ $_LNG = ita ]]; then
-		echo "Lo script è terminato in modo non previsto. Premere un tasto"\
-			"qualsiasi per uscire."
+		echo "Lo script è terminato in modo non previsto. È possibile"\
+			"rileggere i messaggi di errore nel file '/tmp/cleanupdate.log"\
+			"fino al prossimo riavvio. Premere un tasto qualsiasi per"\
+			"uscire." 1>&2
 	else
-		echo "Script terminated unexpectedly. Press any key to exit."
+		echo "Script terminated unexpectedly. It is possible to read error"\
+			"messages also in '/tmp/cleanupdate.log' until the next reboot."\
+			"Press any key to exit." 1>&2
 	fi
 	read -rs -n1
 }
@@ -57,18 +61,20 @@ trap exit_trap EXIT
 logfile="/tmp/cleanupdate.log"
 echo -e "\n$(date -R) --- Cleanupdate errors log\n" >> $logfile
 
-# Define alias to print errors in stderr and in a logfile
-print_errors="tee --append $logfile"
+# Define little function to print errors in stderr and in a logfile
+function print_errors {
+	tee --append $logfile 1>&2
+}
 
 # Check if /bin/tput is installed, otherwise some commands can't work
 if [[ ! -x /bin/tput ]]; then
 	if [[ $_LNG = ita ]]; then
 		echo "ERRORE: /bin/tput non è presente sul sistema, verificare che la"\
-			"libreria 'ncurses' sia installata correttamente." | $print_errors
+			"libreria 'ncurses' sia installata correttamente." | print_errors
 	else
 		echo "ERROR: /bin/tput is not present in the system, verify that"\
 			"verify that 'ncurses' library is properly installed." | \
-			$print_errors
+			print_errors
 	fi
 	exit 1
 fi
@@ -87,10 +93,10 @@ if [[ -z $HOME ]]; then
 	if [[ $_LNG = ita ]]; then
 		echo "ERRORE: la variabile d'ambiente $HOME è vuota,"\
 			"è impossibile ottenere il percorso per la home dell'utente." | \
-			$print_errors
+			print_errors
 	else
 		echo "ERROR: $HOME variable not set properly,"\
-			"it is impossible to get the path of user's home." | $print_errors
+			"it is impossible to get the path of user's home." | print_errors
 	fi
 	exit 1
 fi
@@ -113,10 +119,10 @@ function human_size {
 	else
 		if [[ $_LNG = ita ]]; then
 			echo "ERRORE: impossibile convertire numeri negativi." | \
-				$print_errors
+				print_errors
 		else
 			echo "ERROR: it's not possible to convert negative numbers." | \
-				$print_errors
+				print_errors
 		fi
 		exit 1
 	fi
@@ -165,9 +171,9 @@ function end_msg {
 	else
 		if [[ $_LNG = ita ]]; then
 			echo "ERRORE: modalità sconosciuta, vedere funzione end_msg()." | \
-				$print_errors
+				print_errors
 		else
-			echo "ERROR: unknown option, see end_msg() function." | $print_errors
+			echo "ERROR: unknown option, see end_msg() function." | print_errors
 		fi
 		exit 1
 	fi
@@ -199,10 +205,10 @@ function qst_msg {
 	else
 		if [[ $_LNG = ita ]]; then
 			echo "ERRORE: risposta predefinita sconosciuta, vedere funzione"\
-				"qst_msg()." | $print_errors
+				"qst_msg()." | print_errors
 		else
 			echo "ERROR: unknown default answer, see qst_msg() function." | \
-				$print_errors
+				print_errors
 		fi
 		exit 1
 	fi
@@ -215,8 +221,8 @@ function qst_msg {
 function check_root {
 	if [[ "$(id -u)" = "0" ]]
 	then
-		echo "This script should not be executed as root." | $print_errors
-		echo "Please retry running it as user." | $print_errors
+		echo "This script should not be executed as root." | print_errors
+		echo "Please retry running it as user." | print_errors
 		exit 126
 	fi
 }
@@ -229,18 +235,18 @@ function check_args {
 	if [[ $# -gt 0 ]] ; then
 		if [[ $_LNG = ita ]]; then
 			echo "Errore! Sono stati forniti i seguenti argomenti:" | \
-				$print_errors
+				print_errors
 		else
-			echo "Error! Some arguments have been provided:" | $print_errors
+			echo "Error! Some arguments have been provided:" | print_errors
 		fi
-		echo -en "\t" | $print_errors ; for i in "$@" ; \
-		do echo -n "$i" | $print_errors ; echo -n " " | $print_errors ; done ; \
-		echo | $print_errors ; echo | $print_errors
+		echo -en "\t" | print_errors ; for i in "$@" ; \
+		do echo -n "$i" | print_errors ; echo -n " " | print_errors ; done ; \
+		echo | print_errors ; echo | print_errors
 		if [[ $_LNG = ita ]]; then
 			echo "Cleanupdate non ha bisogno di alcuni argomento." | \
-				$print_errors
+				print_errors
 		else
-			echo "Cleanupdate doesn't need any argument." | $print_errors
+			echo "Cleanupdate doesn't need any argument." | print_errors
 		fi
 		exit 1
 	fi
@@ -1155,11 +1161,10 @@ Premere 'q' per uscire dalla documentazione
 ${_BOLD}${_YELLOW}::Aggiornamento del sistema::${_NORMAL}
 
 ${_BOLD}Aggiornamento dei pacchetti dai repository ufficiali (pacman -Syu)${_NORMAL}
-Controlla che il database locale sia aggiornato, se ci sono differenze tra le versioni dei pacchetti installati e di quelli presenti nel database effettua l'upgrade (innalzamento di versione). Il comando notifica se la versione installata di un pacchetto è più recente di quella nei repository, in questo caso può essere utile eseguire un downgrade (abbassamento di versione) tramite il comando 'pacman -Syuu'.
+Nel caso in cui il sistema installato sia Manjaro Linux viene aggiornata la lista dei mirror nel caso in cui non sia già stata aggiornata nel giorno corrente. Dopodiché controlla che il database locale sia aggiornato, se ci sono differenze tra le versioni dei pacchetti installati e di quelli presenti nel database effettua l'upgrade (innalzamento di versione). Il comando notifica se la versione installata di un pacchetto è più recente di quella nei repository, in questo caso dovrebbe venire proposto automaticamente un downgrade (abbassamento di versione) dei pacchetti problematici, tramite il comando 'pacman -Syuu'.
 
-${_BOLD}Aggiornamento dei pacchetti di AUR (pacaur -Sua else
-yaourt -Sua)${_NORMAL}
-Effettua l'aggiornamento dei pacchetti provenienti dai repository AUR, se necessario. Può utilizzare come strumenti (in ordine di priorità) 'pacaur' oppure 'yaourt'.
+${_BOLD}Aggiornamento dei pacchetti di AUR (pacaur -Sua || yaourt -Sua)${_NORMAL}
+Effettua l'aggiornamento dei pacchetti provenienti dai repository AUR, se necessario. Può utilizzare come strumenti (in ordine di priorità) 'pacaur' oppure 'yaourt'. Prima di controllare gli aggiornamenti lo script esegue un controllo per la presenza di pacchetti orfani, può essere utile se non risolutivo nel caso in cui dei pacchetti installati come dipendenze vengano dismessi dai repository ufficiali di Arch Linux per essere trasferiti nei repository AUR.
 
 ${_BOLD}${_YELLOW}::Pulizia pacchetti::${_NORMAL}
 
